const OWNER = 'JiwaniZakir';
const REPO = 'lifemanagement-kit';
const API = 'https://api.github.com';

interface GitHubFile {
  path: string;
  content: string;
}

function headers(token: string) {
  return {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
  };
}

/**
 * Fork the upstream repo to the authenticated user's account.
 * Returns the fork's full_name (e.g. "username/lifemanagement-kit").
 */
export async function forkRepo(token: string): Promise<{ fullName: string; htmlUrl: string }> {
  const res = await fetch(`${API}/repos/${OWNER}/${REPO}/forks`, {
    method: 'POST',
    headers: headers(token),
    body: JSON.stringify({ default_branch_only: true }),
  });

  if (res.status === 202) {
    const data = await res.json();
    return { fullName: data.full_name, htmlUrl: data.html_url };
  }

  // Fork may already exist — check
  if (res.status === 422) {
    const userRes = await fetch(`${API}/user`, { headers: headers(token) });
    const user = await userRes.json();
    const checkRes = await fetch(`${API}/repos/${user.login}/${REPO}`, {
      headers: headers(token),
    });
    if (checkRes.ok) {
      const data = await checkRes.json();
      return { fullName: data.full_name, htmlUrl: data.html_url };
    }
  }

  const error = await res.json().catch(() => ({}));
  throw new Error(`Failed to fork: ${error.message ?? res.statusText}`);
}

/**
 * Create a feature branch on the user's fork from the default branch.
 */
export async function createFeatureBranch(
  token: string,
  forkFullName: string,
  branchName: string,
): Promise<string> {
  // Get the SHA of the default branch
  const refRes = await fetch(`${API}/repos/${forkFullName}/git/ref/heads/main`, {
    headers: headers(token),
  });
  if (!refRes.ok) {
    throw new Error(`Failed to get main branch ref: ${refRes.statusText}`);
  }
  const refData = await refRes.json();
  const sha = refData.object.sha;

  // Create the new branch
  const createRes = await fetch(`${API}/repos/${forkFullName}/git/refs`, {
    method: 'POST',
    headers: headers(token),
    body: JSON.stringify({
      ref: `refs/heads/${branchName}`,
      sha,
    }),
  });

  if (createRes.status === 422) {
    // Branch already exists — that's fine
    return `https://github.com/${forkFullName}/tree/${branchName}`;
  }

  if (!createRes.ok) {
    const error = await createRes.json().catch(() => ({}));
    throw new Error(`Failed to create branch: ${error.message ?? createRes.statusText}`);
  }

  return `https://github.com/${forkFullName}/tree/${branchName}`;
}

/**
 * Commit multiple files to a branch using the Git Data API (trees + commits + refs).
 */
export async function commitFeatureFiles(
  token: string,
  forkFullName: string,
  branchName: string,
  files: GitHubFile[],
): Promise<string[]> {
  const h = headers(token);

  // 1. Get the current commit SHA for the branch
  const refRes = await fetch(
    `${API}/repos/${forkFullName}/git/ref/heads/${branchName}`,
    { headers: h },
  );
  if (!refRes.ok) throw new Error('Failed to get branch ref');
  const refData = await refRes.json();
  const baseCommitSha = refData.object.sha;

  // 2. Get the tree SHA of that commit
  const commitRes = await fetch(
    `${API}/repos/${forkFullName}/git/commits/${baseCommitSha}`,
    { headers: h },
  );
  if (!commitRes.ok) throw new Error('Failed to get base commit');
  const commitData = await commitRes.json();
  const baseTreeSha = commitData.tree.sha;

  // 3. Create blobs for each file
  const tree = await Promise.all(
    files.map(async (file) => {
      const blobRes = await fetch(`${API}/repos/${forkFullName}/git/blobs`, {
        method: 'POST',
        headers: h,
        body: JSON.stringify({ content: file.content, encoding: 'utf-8' }),
      });
      if (!blobRes.ok) throw new Error(`Failed to create blob for ${file.path}`);
      const blob = await blobRes.json();
      return {
        path: file.path,
        mode: '100644' as const,
        type: 'blob' as const,
        sha: blob.sha,
      };
    }),
  );

  // 4. Create a new tree
  const treeRes = await fetch(`${API}/repos/${forkFullName}/git/trees`, {
    method: 'POST',
    headers: h,
    body: JSON.stringify({ base_tree: baseTreeSha, tree }),
  });
  if (!treeRes.ok) throw new Error('Failed to create tree');
  const treeData = await treeRes.json();

  // 5. Create a new commit
  const newCommitRes = await fetch(`${API}/repos/${forkFullName}/git/commits`, {
    method: 'POST',
    headers: h,
    body: JSON.stringify({
      message: `feat: add feature implementation files\n\nGenerated by Aegis Feature Planner`,
      tree: treeData.sha,
      parents: [baseCommitSha],
    }),
  });
  if (!newCommitRes.ok) throw new Error('Failed to create commit');
  const newCommit = await newCommitRes.json();

  // 6. Update the branch ref to point to the new commit
  const updateRes = await fetch(
    `${API}/repos/${forkFullName}/git/refs/heads/${branchName}`,
    {
      method: 'PATCH',
      headers: h,
      body: JSON.stringify({ sha: newCommit.sha }),
    },
  );
  if (!updateRes.ok) throw new Error('Failed to update branch ref');

  return files.map((f) => f.path);
}
