import { Octokit } from '@octokit/rest';

const OWNER = 'JiwaniZakir';
const REPO = 'lifemanagement-kit';

export async function createFeatureIssue({
  title,
  request,
  plan,
  submitter,
  notes,
  diagramJson,
}: {
  title: string;
  request: string;
  plan: string;
  submitter: string;
  notes?: string;
  diagramJson?: string;
}) {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    throw new Error('GITHUB_TOKEN is not configured');
  }

  const octokit = new Octokit({ auth: token });

  const notesSection = notes
    ? `\n**Contributor notes:**\n> ${notes}\n`
    : '';

  const diagramSection = diagramJson
    ? `\n<details>\n<summary>Architecture Diagram (JSON)</summary>\n\n\`\`\`json\n${diagramJson}\n\`\`\`\n\n</details>\n`
    : '';

  const body = `## Feature Request

> Status: \u23f3 Pending Review

**Submitted by:** ${submitter}

**Original request:**
> ${request}
${notesSection}
---

## AI-Generated Implementation Plan

${plan}
${diagramSection}
---

*This feature request was generated by the [Aegis Feature Planner](https://aegis-docs.vercel.app).*`;

  const response = await octokit.issues.create({
    owner: OWNER,
    repo: REPO,
    title,
    body,
    labels: ['feature-request', 'ai-planned', 'pending-review'],
  });

  return {
    url: response.data.html_url,
    number: response.data.number,
  };
}

export async function listCommunityIssues(filters?: {
  status?: 'all' | 'pending' | 'approved' | 'rejected';
  page?: number;
  perPage?: number;
}) {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    return { issues: [], total: 0, configured: false };
  }

  const octokit = new Octokit({ auth: token });
  const page = filters?.page ?? 1;
  const perPage = filters?.perPage ?? 20;
  const statusFilter = filters?.status ?? 'all';

  const state = statusFilter === 'rejected' ? 'closed' : 'open';

  const { data } = await octokit.issues.listForRepo({
    owner: OWNER,
    repo: REPO,
    labels: 'feature-request',
    state: statusFilter === 'all' ? 'all' : state,
    per_page: perPage,
    page,
    sort: 'created',
    direction: 'desc',
  });

  const issues = data
    .map((issue) => {
      const labels = issue.labels.map((l) =>
        typeof l === 'string' ? l : l.name ?? '',
      );

      let status: 'pending' | 'approved' | 'rejected' = 'pending';
      if (labels.includes('approved')) status = 'approved';
      if (labels.includes('rejected') || issue.state === 'closed') status = 'rejected';

      // Extract submitter from issue body
      const submitterMatch = issue.body?.match(/\*\*Submitted by:\*\*\s*(.+)/);
      const submitter = submitterMatch?.[1]?.trim() ?? 'Anonymous';

      return {
        number: issue.number,
        title: issue.title.replace(/^\[Feature\]\s*/i, ''),
        submitter,
        status,
        labels,
        createdAt: issue.created_at,
        url: issue.html_url,
      };
    })
    .filter((i) => statusFilter === 'all' || i.status === statusFilter);

  return { issues, total: issues.length, configured: true };
}

export async function getIssueStatus(issueNumber: number) {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    throw new Error('GITHUB_TOKEN is not configured');
  }

  const octokit = new Octokit({ auth: token });

  const { data } = await octokit.issues.get({
    owner: OWNER,
    repo: REPO,
    issue_number: issueNumber,
  });

  const labels = data.labels.map((l) =>
    typeof l === 'string' ? l : l.name ?? '',
  );

  let status: 'pending' | 'approved' | 'rejected' = 'pending';
  if (labels.includes('approved')) status = 'approved';
  if (labels.includes('rejected') || data.state === 'closed') status = 'rejected';

  return {
    status,
    url: data.html_url,
    title: data.title,
  };
}
