import { Octokit } from '@octokit/rest';

const OWNER = 'JiwaniZakir';
const REPO = 'lifemanagement-kit';

export async function createFeatureIssue({
  title,
  request,
  plan,
  submitter,
}: {
  title: string;
  request: string;
  plan: string;
  submitter: string;
}) {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    throw new Error('GITHUB_TOKEN is not configured');
  }

  const octokit = new Octokit({ auth: token });

  const body = `## Feature Request

**Submitted by:** ${submitter}

**Original request:**
> ${request}

---

## AI-Generated Implementation Plan

${plan}

---

*This feature request was generated by the [Aegis Feature Planner](https://aegis-docs.vercel.app).*`;

  const response = await octokit.issues.create({
    owner: OWNER,
    repo: REPO,
    title,
    body,
    labels: ['feature-request', 'ai-planned'],
  });

  return {
    url: response.data.html_url,
    number: response.data.number,
  };
}
