import type { SkillInfo } from '@/lib/types/planner';

export const AEGIS_SKILLS: SkillInfo[] = [
  {
    id: 'aegis-finance',
    name: 'Finance',
    description: 'Banking transactions, investment portfolios, and spending insights via Plaid and Schwab.',
    icon: 'DollarSign',
    integrations: ['Plaid', 'Schwab'],
    capabilities: ['Transaction sync', 'Portfolio tracking', 'Spending analysis'],
    endpointCount: 6,
    color: '#22c55e',
  },
  {
    id: 'aegis-calendar',
    name: 'Calendar',
    description: 'Events from Google and Outlook calendars with free-slot detection and scheduling.',
    icon: 'Calendar',
    integrations: ['Google Calendar', 'Outlook'],
    capabilities: ['Event sync', 'Free slots', 'Schedule conflicts'],
    endpointCount: 4,
    color: '#3b82f6',
  },
  {
    id: 'aegis-lms',
    name: 'LMS',
    description: 'Canvas and Blackboard assignment tracking with deadlines and grade monitoring.',
    icon: 'GraduationCap',
    integrations: ['Canvas', 'Blackboard'],
    capabilities: ['Assignment tracking', 'Grade monitoring', 'Deadline alerts'],
    endpointCount: 3,
    color: '#f59e0b',
  },
  {
    id: 'aegis-health',
    name: 'Health',
    description: 'Health metrics from Garmin Connect including steps, heart rate, and sleep data.',
    icon: 'Heart',
    integrations: ['Garmin Connect'],
    capabilities: ['Activity metrics', 'Sleep tracking', 'Health goals'],
    endpointCount: 3,
    color: '#ec4899',
  },
  {
    id: 'aegis-social',
    name: 'Social',
    description: 'Post to LinkedIn and X with scheduling and engagement tracking.',
    icon: 'Share2',
    integrations: ['LinkedIn', 'X'],
    capabilities: ['Post publishing', 'Schedule posts', 'Engagement tracking'],
    endpointCount: 4,
    color: '#7c6aef',
  },
  {
    id: 'aegis-content',
    name: 'Content',
    description: 'AI-powered content generation with draft lifecycle and editorial workflow.',
    icon: 'PenTool',
    integrations: ['AI Models'],
    capabilities: ['Draft generation', 'Editorial review', 'Content strategy'],
    endpointCount: 3,
    color: '#06b6d4',
  },
  {
    id: 'aegis-briefing',
    name: 'Briefing',
    description: 'Daily morning briefs and weekly digests aggregating all data sources.',
    icon: 'Newspaper',
    integrations: ['All sources'],
    capabilities: ['Morning brief', 'Weekly digest', 'Priority alerts'],
    endpointCount: 2,
    color: '#8b7cf7',
  },
  {
    id: 'aegis-security',
    name: 'Security',
    description: 'PII awareness, audit chain verification, and encrypted credential management.',
    icon: 'Shield',
    integrations: ['Internal'],
    capabilities: ['PII redaction', 'Audit logging', 'Secret rotation'],
    endpointCount: 3,
    color: '#ef4444',
  },
];
