import type { SkillInfo } from '@/lib/types/planner';

export interface WorkflowStep {
  label: string;
  detail: string;
}

export interface SkillDetail extends SkillInfo {
  tagline: string;
  workflow: WorkflowStep[];
  dataFlow: string;
  example: string;
}

export const AEGIS_SKILLS: SkillDetail[] = [
  {
    id: 'aegis-finance',
    name: 'Finance',
    description: 'See where your money goes and how your investments perform — all in one place.',
    tagline: 'Your money, understood',
    icon: 'DollarSign',
    integrations: ['Plaid', 'Schwab'],
    capabilities: ['Spending insights', 'Portfolio tracking', 'Budget alerts'],
    endpointCount: 6,
    color: '#22c55e',
    workflow: [
      { label: 'Connect', detail: 'Securely link your bank and brokerage accounts' },
      { label: 'Sync', detail: 'Transactions and holdings update automatically' },
      { label: 'Protect', detail: 'Everything encrypted before it\u2019s stored' },
      { label: 'Understand', detail: 'AI finds patterns in your spending and investments' },
      { label: 'Know', detail: 'Get insights on WhatsApp whenever you ask' },
    ],
    dataFlow: 'Your accounts \u2192 Aegis \u2192 Encrypted storage \u2192 AI analysis \u2192 WhatsApp',
    example: '\u201cHow much did I spend on food this month?\u201d \u2192 $847 across 23 transactions',
  },
  {
    id: 'aegis-calendar',
    name: 'Calendar',
    description: 'All your calendars merged. Know when you\u2019re free, catch conflicts early.',
    tagline: 'Never double-book again',
    icon: 'Calendar',
    integrations: ['Google Calendar', 'Outlook'],
    capabilities: ['Unified view', 'Free slots', 'Conflict detection'],
    endpointCount: 4,
    color: '#3b82f6',
    workflow: [
      { label: 'Link', detail: 'Connect Google and Outlook calendars' },
      { label: 'Merge', detail: 'Events combined into one unified timeline' },
      { label: 'Analyze', detail: 'Free slots and conflicts detected automatically' },
      { label: 'Brief', detail: 'Today\u2019s schedule included in your morning brief' },
      { label: 'Ask', detail: 'Ask when you\u2019re free and get instant answers' },
    ],
    dataFlow: 'Google & Outlook \u2192 Aegis \u2192 Unified calendar \u2192 AI \u2192 WhatsApp',
    example: '\u201cWhen am I free tomorrow?\u201d \u2192 10:00\u201311:30 AM and 2:00\u20134:00 PM',
  },
  {
    id: 'aegis-lms',
    name: 'Education',
    description: 'Track assignments, deadlines, and grades across all your courses.',
    tagline: 'Stay on top of coursework',
    icon: 'GraduationCap',
    integrations: ['Canvas', 'Blackboard'],
    capabilities: ['Deadline tracking', 'Grade alerts', 'Weekly summaries'],
    endpointCount: 3,
    color: '#f59e0b',
    workflow: [
      { label: 'Connect', detail: 'Link your Canvas or Blackboard account' },
      { label: 'Scan', detail: 'Courses, assignments, and grades pulled automatically' },
      { label: 'Track', detail: 'Deadlines monitored with countdown alerts' },
      { label: 'Remind', detail: 'Get reminders 48h and 24h before due dates' },
      { label: 'Review', detail: 'Weekly digest shows GPA trends and upcoming work' },
    ],
    dataFlow: 'Canvas & Blackboard \u2192 Aegis \u2192 Deadline engine \u2192 AI \u2192 WhatsApp',
    example: '\u201cWhat\u2019s due this week?\u201d \u2192 3 assignments: CS301 lab, Math hw, Essay',
  },
  {
    id: 'aegis-health',
    name: 'Health',
    description: 'Steps, sleep, heart rate — your health data summarized and actionable.',
    tagline: 'Your body, quantified',
    icon: 'Heart',
    integrations: ['Garmin Connect'],
    capabilities: ['Activity tracking', 'Sleep analysis', 'Goal progress'],
    endpointCount: 3,
    color: '#ec4899',
    workflow: [
      { label: 'Pair', detail: 'Connect your Garmin wearable' },
      { label: 'Collect', detail: 'Steps, heart rate, sleep, and body battery synced daily' },
      { label: 'Store', detail: 'Health history builds over time' },
      { label: 'Goals', detail: 'Track progress against your personal targets' },
      { label: 'Brief', detail: 'Morning brief includes yesterday\u2019s activity recap' },
    ],
    dataFlow: 'Garmin wearable \u2192 Aegis \u2192 Health history \u2192 AI \u2192 WhatsApp',
    example: '\u201cHow did I sleep?\u201d \u2192 7h 23m, 92% quality, 1h 45m deep sleep',
  },
  {
    id: 'aegis-social',
    name: 'Social',
    description: 'Post to LinkedIn and X with scheduling and engagement tracking.',
    tagline: 'Publish from your pocket',
    icon: 'Share2',
    integrations: ['LinkedIn', 'X'],
    capabilities: ['One-tap posting', 'Smart scheduling', 'Engagement stats'],
    endpointCount: 4,
    color: '#7c6aef',
    workflow: [
      { label: 'Draft', detail: 'AI generates post ideas from your strategy' },
      { label: 'Review', detail: 'Approve or tweak via WhatsApp' },
      { label: 'Schedule', detail: 'Published at the optimal time automatically' },
      { label: 'Post', detail: 'Goes live on LinkedIn and X simultaneously' },
      { label: 'Measure', detail: 'Engagement stats tracked and reported back' },
    ],
    dataFlow: 'AI draft \u2192 Your approval \u2192 Scheduled publish \u2192 Engagement tracking',
    example: '\u201cPost my latest article\u201d \u2192 Published to LinkedIn & X with tracking',
  },
  {
    id: 'aegis-content',
    name: 'Content',
    description: 'AI writes thought-leadership posts. You approve. It learns what works.',
    tagline: 'Content on autopilot',
    icon: 'PenTool',
    integrations: ['AI Models'],
    capabilities: ['Auto-drafting', 'Editorial flow', 'Performance learning'],
    endpointCount: 3,
    color: '#06b6d4',
    workflow: [
      { label: 'Define', detail: 'Set your content pillars and voice' },
      { label: 'Generate', detail: 'AI writes drafts aligned to your strategy' },
      { label: 'Refine', detail: 'Review and edit conversationally on WhatsApp' },
      { label: 'Publish', detail: 'Approved drafts flow to the social skill' },
      { label: 'Learn', detail: 'Performance data improves future drafts' },
    ],
    dataFlow: 'Your strategy \u2192 AI drafts \u2192 Your edits \u2192 Publish \u2192 Learn',
    example: '\u201cWrite a post about AI agents\u201d \u2192 Draft ready for your review',
  },
  {
    id: 'aegis-briefing',
    name: 'Briefing',
    description: 'Everything that matters, every morning. One message, zero noise.',
    tagline: 'Your day at a glance',
    icon: 'Newspaper',
    integrations: ['All sources'],
    capabilities: ['Morning brief', 'Weekly digest', 'Priority alerts'],
    endpointCount: 2,
    color: '#8b7cf7',
    workflow: [
      { label: 'Gather', detail: 'Pull from finance, calendar, health, school, social' },
      { label: 'Merge', detail: 'All sources combined into one picture' },
      { label: 'Rank', detail: 'AI prioritizes by urgency and importance' },
      { label: 'Compose', detail: 'Clean summary with actionable highlights' },
      { label: 'Deliver', detail: 'Arrives on WhatsApp at 7 AM daily' },
    ],
    dataFlow: 'All your data \u2192 AI prioritization \u2192 Formatted brief \u2192 WhatsApp',
    example: '3 meetings, 2 assignments due, $247 spent yesterday, 8.2k steps',
  },
  {
    id: 'aegis-security',
    name: 'Security',
    description: 'Your data is encrypted, audited, and protected — automatically.',
    tagline: 'Privacy by default',
    icon: 'Shield',
    integrations: ['Built-in'],
    capabilities: ['Auto-redaction', 'Audit trail', 'Encryption'],
    endpointCount: 3,
    color: '#ef4444',
    workflow: [
      { label: 'Scan', detail: 'Every outbound message checked for sensitive data' },
      { label: 'Redact', detail: 'SSNs, card numbers, and personal info auto-masked' },
      { label: 'Log', detail: 'Tamper-proof audit trail of all activity' },
      { label: 'Encrypt', detail: 'All stored data protected with military-grade encryption' },
      { label: 'Rotate', detail: 'Secrets automatically refreshed on a 90-day cycle' },
    ],
    dataFlow: 'Your data \u2192 Encryption \u2192 Audit log \u2192 Secure storage',
    example: 'SSN: 123-45-6789 \u2192 automatically redacted to SSN: ***-**-****',
  },
];
