interface CloudInitOptions {
  webhookUrl: string;
  webhookSecret: string;
  anthropicKey: string;
  whatsappPhone: string;
  instanceName: string;
  enabledIntegrations: string[];
  cloudflareToken: string;
  tunnelName: string;
}

/**
 * Escape a value for safe inclusion in a bash script.
 * Wraps in single quotes with proper escaping.
 */
function bashEscape(val: string): string {
  return "'" + val.replace(/'/g, "'\\''") + "'";
}

/**
 * Generate a cloud-init user_data bash script.
 *
 * Architecture: Vercel has a 60s serverless timeout, so SSH is impossible.
 * Instead, cloud-init runs on the server and POSTs webhook callbacks per step.
 * The frontend polls GET /api/deploy/[id]/status every 3s.
 */
export function generateCloudInit(opts: CloudInitOptions): string {
  // Pre-escape all user-supplied values for bash safety
  const webhookUrl = bashEscape(opts.webhookUrl);
  const webhookSecret = bashEscape(opts.webhookSecret);
  const anthropicKey = bashEscape(opts.anthropicKey);
  const whatsappPhone = bashEscape(opts.whatsappPhone);
  const instanceName = bashEscape(opts.instanceName);
  const integrations = bashEscape(opts.enabledIntegrations.join(','));
  const cfToken = bashEscape(opts.cloudflareToken);

  return `#!/bin/bash
set -euo pipefail

export DEBIAN_FRONTEND=noninteractive

WEBHOOK_URL=${webhookUrl}
WEBHOOK_SECRET=${webhookSecret}

report() {
  local step="$1"
  local msg="$2"
  curl -sf -X POST "$WEBHOOK_URL" \\
    -H "Content-Type: application/json" \\
    -H "X-Webhook-Secret: $WEBHOOK_SECRET" \\
    -d "{\\"step\\":\\"$step\\",\\"message\\":\\"$msg\\",\\"timestamp\\":\\"$(date -u +%FT%TZ)\\"}" \\
    || true
}

report "creating_server" "Server created, starting installation"

# ── Step 1: Install Docker ──
report "installing" "Installing Docker and dependencies"
apt-get update -qq
apt-get install -y -qq docker.io docker-compose-v2 git curl jq
systemctl enable docker
systemctl start docker

# ── Step 2: Clone repo ──
report "cloning" "Cloning Aegis repository"
cd /opt
git clone --depth 1 https://github.com/JiwaniZakir/lifemanagement-kit.git aegis
cd aegis

# ── Step 3: Generate secrets and write .env ──
report "bootstrapping" "Generating secrets and writing configuration"
DATA_API_TOKEN=$(openssl rand -hex 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)
POSTGRES_PASSWORD=$(openssl rand -hex 16)
OPENCLAW_GATEWAY_TOKEN=$(openssl rand -hex 32)

cat > .env << EOF
# Aegis Instance: ${opts.instanceName}
# Generated by Aegis Deploy Platform

ANTHROPIC_API_KEY=${anthropicKey}
DATA_API_TOKEN=$DATA_API_TOKEN
ENCRYPTION_KEY=$ENCRYPTION_KEY
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
WHATSAPP_PHONE=${whatsappPhone}
INSTANCE_NAME=${instanceName}
OPENCLAW_GATEWAY_TOKEN=$OPENCLAW_GATEWAY_TOKEN
ENABLED_INTEGRATIONS=${integrations}
EOF

# ── Step 4: Bootstrap ──
report "bootstrapping" "Running database migrations"
if [ -f infrastructure/scripts/bootstrap.sh ]; then
  chmod +x infrastructure/scripts/bootstrap.sh
  bash infrastructure/scripts/bootstrap.sh || true
fi

# ── Step 5: Start services ──
report "configuring" "Starting Docker services"
docker compose up -d

# ── Step 6: Cloudflare Tunnel ──
report "configuring" "Setting up Cloudflare Tunnel"
curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
dpkg -i cloudflared.deb
rm -f cloudflared.deb

# Use connector install which runs cloudflared as a systemd service
# The token contains tunnel ID + credentials baked in
cloudflared service install ${cfToken} || true
systemctl enable cloudflared || true
systemctl start cloudflared || true

# ── Step 7: Health check ──
report "health_check" "Waiting for services to become healthy"
sleep 15

HEALTHY=false
for i in $(seq 1 20); do
  if curl -sf http://127.0.0.1:8000/health > /dev/null 2>&1; then
    HEALTHY=true
    break
  fi
  sleep 5
done

if [ "$HEALTHY" = true ]; then
  report "completed" "All services healthy — Aegis is ready"
else
  report "completed" "Deployment finished — services may still be starting"
fi
`;
}
