import { randomBytes } from 'crypto';
import JSZip from 'jszip';

interface BundleOptions {
  instanceName: string;
  anthropicKey: string;
  whatsappPhone: string;
  enabledIntegrations: string[];
}

/**
 * Generate an in-memory ZIP containing everything needed for local deployment.
 */
export async function generateLocalBundle(opts: BundleOptions): Promise<ArrayBuffer> {
  const zip = new JSZip();

  // docker-compose.yml
  zip.file('docker-compose.yml', `version: "3.9"

services:
  openclaw-gateway:
    image: ghcr.io/openclaw/openclaw:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:18789:18789"
    volumes:
      - ./config:/app/config
      - ./skills:/app/skills
      - ./hooks:/app/hooks
      - openclaw-data:/app/data
    environment:
      - ANTHROPIC_API_KEY=\${ANTHROPIC_API_KEY}
      - DATA_API_URL=http://data-api:8000
      - DATA_API_TOKEN=\${DATA_API_TOKEN}
    depends_on:
      data-api:
        condition: service_healthy
    networks:
      - frontend
      - backend

  data-api:
    build:
      context: .
      dockerfile: infrastructure/Dockerfile.data-api
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://aegis:\${POSTGRES_PASSWORD}@postgres:5432/aegis
      - DATA_API_TOKEN=\${DATA_API_TOKEN}
      - ENCRYPTION_KEY=\${ENCRYPTION_KEY}
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
      - data
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=aegis
      - POSTGRES_USER=aegis
      - POSTGRES_PASSWORD=\${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aegis"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - data
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=\${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - frontend
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  openclaw-data:
  postgres-data:

networks:
  frontend:
  backend:
    internal: true
  data:
    internal: true
`);

  // .env
  zip.file('.env', `# Aegis Environment Configuration
# Instance: ${opts.instanceName}
# Generated by Aegis Deploy

ANTHROPIC_API_KEY=${opts.anthropicKey}
DATA_API_TOKEN=${crypto.randomUUID()}
ENCRYPTION_KEY=${crypto.randomUUID()}
POSTGRES_PASSWORD=${crypto.randomUUID().replace(/-/g, '')}
OPENCLAW_GATEWAY_TOKEN=${randomBytes(32).toString('hex')}
WHATSAPP_PHONE=${opts.whatsappPhone}
ENABLED_INTEGRATIONS=${opts.enabledIntegrations.join(',')}

# Cloudflare Tunnel (optional — fill in after creating tunnel)
# CLOUDFLARE_TUNNEL_TOKEN=
`);

  // bootstrap.sh
  zip.file('bootstrap.sh', `#!/bin/bash
set -euo pipefail

echo "==> Starting Aegis bootstrap..."

# Pull images
docker compose pull

# Start database first
docker compose up -d postgres
echo "==> Waiting for PostgreSQL..."
sleep 5

# Run migrations
docker compose run --rm data-api alembic upgrade head

# Start all services
docker compose up -d

echo "==> Aegis is starting up!"
echo "==> Gateway: http://localhost:18789"
echo "==> Data API: http://localhost:8000 (internal)"
echo ""
echo "==> To pair WhatsApp, visit the gateway UI."
`);

  // README
  zip.file('README-quickstart.md', `# Aegis Quick Start

## Prerequisites
- Docker & Docker Compose v2
- Anthropic API key (already configured in .env)

## Setup
\`\`\`bash
chmod +x bootstrap.sh
./bootstrap.sh
\`\`\`

## Access
- Gateway UI: http://localhost:18789
- Pair WhatsApp by scanning the QR code in the gateway UI

## Integrations
Enabled: ${opts.enabledIntegrations.join(', ') || 'none'}

Configure credentials through the gateway UI or data-api.
`);

  const buffer = await zip.generateAsync({ type: 'arraybuffer' });
  return buffer;
}
